version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "awsKpi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1gep3dr2n4saq"
s3_prefix = "awsKpi"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
